[System]
arcade = false
playable = 3
menuTimer = 90

[Window]
width = 1920
height = 1080
sizable = true
fullscreen = false
letterboxColor = "#000000"

[Sheet]
mock = true

[Controller]
device = "keyboard"
port = "COM1"
baudrate = 115200
threshold = 1
latencyOffset = 0.06575

[CardReader]
device = "mock"
mockId = "00000000"

[Api]
mock = true
endpoint = "https://api.example.com"
